number: '0123456789'
symbol: "-"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'  # No usar 'None', especificar directamente
experiment_name: 'en_licenseplate_test'
train_data: '/home/ricardo/Documents/Proactif/data/vehicle_plate_recognition/Number_plate_ocr_dataset/dataset/train'
valid_data: '/home/ricardo/Documents/Proactif/data/vehicle_plate_recognition/Number_plate_ocr_dataset/dataset/val'
manualSeed: 1111
workers: 1  # Cambiar a 1 para Jupyter Notebook (evita problemas de multiprocessing)
batch_size: 8 #32
num_iter: 300000
valInterval: 20000
saved_model: 'saved_models/latin_g2.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: True
optim: False # default is Adadelta
lr: 0.01 # lr original de 1. , pruebo uno más bajo para hacer fine tunning
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: '' # Buscar en toda la jerarquía de train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 300 # valor por defecto: 600, lo dejo en 300 para conservar el ratio de aspecto cercano al original
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: True  # Reemplazar capa de predicción para los 38 caracteres
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
# Fine-tuning parameters
lang_char: 'None'  # Auto-generate from dataset (only 38 chars)